### PR TITLE
added Medium icon

### PR DESCRIPTION
**Pull request by abhinav1107**
Hi.

I was looking for [Medium](https://medium.com/) icon. Didn't find it, so tried adding it.

Screenshot 2023-12-25 at 21 03 35

If this doesn't go well with the rest of the icons, could you please add one?

Thank you.

### CODE REVIEW

**Comment by 1bl4z3r** [comment]
Hi @abhinav1107,

Can you check if logo is of same dimensions as that of Etsy, and doesn't look out of order.

Meanwhile I will check this from my end too.

**Comment by 1bl4z3r** [comment]
Hi @abhinav1107,

The icon you have provided looks a tad bit small wrt other icons (Github, Mastodon and X).
I will try to make a slightly bigger version of the same.

image

**Comment by 1bl4z3r** [comment]
Hello again,
I found that logo for [Medium](https://medium.com/) is these three blobs
image

So, I have tried to implement the same here. I used this svg 

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" class="feather feather-archive"><path d="M13.54 12a6.8 6.8 0 0 1-6.77 6.82A6.8 6.8 0 0 1 0 12a6.8 6.8 0 0 1 6.77-6.82A6.8 6.8 0 0 1 13.54 12Zm7.42 0c0 3.54-1.51 6.42-3.38 6.42-1.87 0-3.39-2.88-3.39-6.42s1.52-6.42 3.39-6.42 3.38 2.88 3.38 6.42ZM24 12c0 3.17-.53 5.75-1.19 5.75-.66 0-1.19-2.58-1.19-5.75s.53-5.75 1.19-5.75C23.47 6.25 24 8.83 24 12Z" fill="currentColor"/>
```

image

Let me know if you want prefer one over the other, or any suggestions on the same

**Comment by abhinav1107** [comment]
Hi.

didn't have access to email for last 2 days.

This is awesome. Both works for me. Honestly, its your baby. You should pick the final version of the logo.. I am just happy that something like hermit-v2 exists, which is exactly what I was looking for. In case you absolutely insist on me picking, I recon we should go with current logo (the circle ones).

Thanks again.

**Comment by 1bl4z3r** [comment]
Very well then 😀

I shall use the new logo for Medium.

I shall merge your PR too, as it is your contribution and I will respect that. Your contribution will thereby be named as `alt_medium`

Expect all things done within a couple of days.

> And no, hermit-v2 isn't my baby. It is a baby of all of the Open Source Contributors like you

**Comment by 1bl4z3r** [comment]
Hi @abhinav1107,

Your PR is merged.
Cheers!!

And, wish you a Happy New year

**Comment by abhinav1107** [comment]
Thank you. And Happy New Year to you too.

**Pull request merged**
